// utils/categories.js

export const categories = [
  { catId: 0, text: '全部', use_home_grid: false, use_list: true, grid_column: 3, grid_row: 3, skills: [],
    is_active: true,
    sort_order: 0 },
  {
    catId: 1,
    key: 'neighborhood',
    text: '邻帮',
    name: '邻帮',
    description: '邻里之间互相帮助的服务',
    icon: '/static/grids/Neighborhood.png',
    route: '/pages/category-tasks/index?catId=1&catName=邻帮',
    use_home_grid: true,
    use_list: true,
    is_map_skill: true,
    skills: [
      '家教兼职',
      '上门理发',
      '律师咨询',
      '医生问诊',
      '建筑师设计',
      '家装设计师',
      '护士护理',
      '心理咨询',
      '财务咨询',
      '翻译服务',
      '代驾服务',
      '搬家服务',
      '装修咨询',
      '园艺服务',
      '临时看护'
    ],
    is_active: true,
    sort_order: 1
  },
  {
    catId: 2,
    key: 'errand',
    text: '跑腿',
    name: '跑腿',
    description: '日常跑腿配送服务',
    icon: '/static/grids/delivery.png',
    route: '/pages/category-tasks/index?catId=2&catName=跑腿',
    use_home_grid: true,
    use_list: true,
    is_map_skill: true,
    skills: [
      '校园跑腿',
      '快递代取',
      '外卖代取',
      '生鲜配送',
      '文件代送',
      '药品代购',
      '生活用品代购',
      '文件打印',
      '排队代购',
      '包裹代收'
    ],
    is_active: true,
    sort_order: 2
  },
  {
    catId: 3,
    key: 'housekeeping',
    text: '家政',
    name: '家政',
    description: '家庭生活相关服务',
    icon: '/static/grids/Housekeeping.png',
    route: '/pages/category-tasks/index?catId=3&catName=家政',
    use_home_grid: true,
    use_list: true,
    is_map_skill: true,
    skills: [
      '生活收纳师',
      '保洁服务',
      '母婴护理',
      '月嫂服务',
      '老人护理',
      '病患护理',
      '家庭厨师',
      '管家服务',
      '洗衣熨烫',
      '家居整理',
      '深度清洁',
      '家电清洗',
      '玻璃清洗',
      '地毯清洗',
      '帘纱洗换',
      '除醛除螨',
      '除尘除渍'
    ],
    is_active: true,
    sort_order: 3
  },
  {
    catId: 4,
    key: 'pet',
    text: '宠物',
    name: '宠物',
    description: '宠物相关服务',
    icon: '/static/grids/PetCare.png',
    route: '/pages/category-tasks/index?catId=4&catName=宠物',
    use_home_grid: true,
    use_list: true,
    is_map_skill: true,
    skills: [
      '宠物医生',
      '宠物美容',
      '宠物寄养',
      '遛狗服务',
      '宠物训练',
      '宠物护理',
      '宠物用品',
      '宠物殡葬',
      '宠物营养师',
      '行为矫正',
      '宠物急救',
      '疫苗接种',
      '绝育手术',
      '宠物体检',
      '宠物按摩',
      '宠物SPA',
      '宠物社交'
    ],
    is_active: true,
    sort_order: 4
  },
  {
    catId: 5,
    key: 'maintenance',
    text: '维修',
    name: '维修',
    description: '各类设备维修服务',
    icon: '/static/grids/Maintenance.png',
    route: '/pages/category-tasks/index?catId=5&catName=维修',
    use_home_grid: true,
    use_list: true,
    is_map_skill: true,
    skills: [
      '修手机',
      '修电脑',
      '防水补漏',
      '水电维修',
      '家电维修',
      '家具维修',
      '门窗维修',
      '管道疏通',
      '网络维修',
      '地暖维修',
      '电梯维修',
      '安防系统维修'
    ],
    is_active: true,
    sort_order: 5
  },
  {
    catId: 6,
    key: 'medical',
    text: '陪诊',
    name: '陪诊',
    description: '医疗陪护相关服务',
    icon: '/static/grids/MedicalEscort.png',
    route: '/pages/category-tasks/index?catId=6&catName=陪诊',
    use_home_grid: true,
    use_list: true,
    is_map_skill: true,
    skills: [
      '陪诊师',
      '高级护理师',
      '营养师',
      '康复师',
      '理疗师',
      '心理咨询师',
      '体检陪护',
      '手术陪护',
      '住院陪护',
      '老人陪诊',
      '慢性病管理',
      '健康管理师'
    ],
    is_active: true,
    sort_order: 6
  },
  {
    catId: 7,
    key: 'job-market',
    text: '趴活广场',
    name: '趴活广场',
    description: '趴活广场',
    icon: '/static/grids/JobMarket.png',
    route: '/pages/parjob-square/index',
    use_home_grid: true,
    use_list: false,
    is_map_skill: false,
    skills: [],
    is_active: true,
    sort_order: 7
  },
  {
    catId: 8,
    key: 'fitness',
    text: '健身',
    name: '健身',
    description: '运动健身相关服务',
    icon: '/static/grids/sportTogether.png',
    route: '/pages/category-tasks/index?catId=8&catName=健身',
    use_home_grid: true,
    use_list: true,
    is_map_skill: true,
    skills: [
      '羽毛球',
      '单杠训练',
      '轮滑',
      '台球',
      '篮球',
      '晨跑夜跑',
      '健身房指导',
      '瑜伽教练',
      '普拉提',
      '游泳教练',
      '网球教练',
      '乒乓球',
      '足球',
      '排球',
      '攀岩',
      '滑雪',
      '滑板',
      '骑行',
      '力量训练'
    ],
    is_active: true,
    sort_order: 8
  },
  {
    catId: 9,
    key: 'travel',
    text: '旅行',
    name: '旅行',
    description: '旅游出行相关服务',
    icon: '/static/grids/toTravel.png',
    route: '/pages/category-tasks/index?catId=9&catName=旅行',
    use_home_grid: true,
    use_list: true,
    is_map_skill: true,
    skills: [
      '打卡攻略',
      '爬山',
      '自驾游',
      '旅游规划',
      '导游服务',
      '摄影指导',
      '户外探险',
      '民宿推荐',
      '文化体验',
      '亲子游',
      '情侣游',
      '团队游',
      '定制旅行',
      '租车服务',
      '地陪'
    ],
    is_active: true,
    sort_order: 9
  },
  {
    catId: 10,
    key: 'food',
    text: '吃喝',
    name: '吃喝',
    description: '美食餐饮相关服务',
    icon: '/static/grids/foods.png',
    route: '/pages/category-tasks/index?catId=10&catName=吃喝',
    use_home_grid: true,
    use_list: true,
    is_map_skill: true,
    skills: [
      '特色美食',
      '上门做菜',
      '烘焙师',
      '咖啡师',
      '调酒师',
      '茶艺师',
      '品酒师',
      '美食探店',
      '团餐打卡',
      '私房菜',
      '减肥餐',
      '增肌餐',
      '素食料理',
      '西餐制作',
      '日料制作'
    ],
    is_active: true,
    sort_order: 10
  },
  {
    catId: 99,
    key: 'entertainment',
    text: '更多',
    name: '更多',
    description: '大家一起娱乐活动',
    icon: '/static/grids/more.png',
    route: '/pages/category-tasks/index?catId=99&catName=更多',
    use_home_grid: true,
    use_list: true,
    is_map_skill: true,
    skills: [
      '出游',
      '打球',
      '轰趴',
      '电竞',
      '桌游',
      'KTV',
      '密室逃脱',
      '剧本杀',
      '野餐',
      '烧烤',
      '露营',
      '徒步',
      '摄影',
      '绘画',
      '手工DIY',
      '音乐',
      '舞蹈',
      '瑜伽',
      '冥想',
      '读书会'
    ],
    is_active: true,
    sort_order: 99
  }
]
